SourenP/ungroup_game

src/client/NetworkingClient.hpp
src/server/NetworkingServer.cpp

Disconnecting wouldn't remove from the selector, but it would free the
socket. For whatever reason this meant after a client disconnected
another wouldn't be able to connect.
I also fixed a compilation error when building on Linux - an include was
missing for the atomic std lib. Not sure why it didn't trigger on OS X.
ALSO following bad commit message hygiene, but there was a bug where I
couldn't run multiple clients at the same time because they were all
binding to the same port 4846. I bind to 0 now which selects any
available port.

Fix bug in disconnecting

---

src/common/ThreadSafeVector.hpp
src/common/game_def.hpp
src/server/GameController.cpp
src/server/GameController.hpp
src/server/LevelController.cpp
src/server/LevelController.hpp
src/server/NetworkingServer.cpp
src/server/NetworkingServer.hpp

We used to have a function called `refreshPlayers` which would infer which client_ids were added/removed. This is inefficient and complicated. Instead `NetworkingServer` now communicates the new/removed client ids and players are updated accordingly in `updatePlayers`

Improve the way players are refreshed on client connect/disconnect

---

src/client/systems/ClientGameController.cpp
src/client/systems/NetworkingClient.cpp
src/client/systems/NetworkingClient.hpp
src/common/util/game_def.hpp
src/common/util/game_settings.hpp
src/common/util/network_util.cpp
src/common/util/network_util.hpp
src/server/systems/NetworkingServer.cpp
src/server/systems/NetworkingServer.hpp

- Add sleeps to threads to limit cpu usage
- Broadcast game state to all clients constantly instead of having
clients ask for it
- Have server and client send udp ports to eachother over the initial
tcp registration communication
- Clean up networking code

Networking thread improvements

---

src/client/CMakeLists.txt
src/server/CMakeLists.txt

Use server and client lib in their own executables to avoid compiling same files twice

---

src/common/physics/CollisionUtil.cpp
src/common/physics/CollisionUtil.hpp
src/common/physics/PhysicsController.cpp
src/common/physics/PhysicsDef.hpp
src/common/physics/VectorUtil.cpp
tests/common/physics/tests-CollisionUtil.cpp

I've also added an impulse multiplier. Groups/Mines now 'bounce' off each other when colliding.

Do not resolve collision if bodies are moving away from each other

---

src/client/systems/ClientGameController.cpp
src/client/systems/NetworkingClient.cpp
src/client/systems/NetworkingClient.hpp
src/common/objects/Player.cpp
src/common/systems/GameController.cpp
src/common/systems/PlayerController.cpp
src/common/util/StateDef.cpp
src/common/util/StateDef.hpp
src/common/util/Util.hpp

Fixes  #103
[fd5b091] Client input improvements
- Send toggle of toggle unreliable inputs instead of sending a computed
value e.g. up=true instead of direction=(0,-1)
- Only send client inputs to server when present
- Only apply client inputs once in an update. This was a bug before
where we would apply it "step" amount of times. A single update can have
many steps.

Client input improvements

---

.clang-format
.travis.yml
src/client/main.cpp
src/client/systems/ClientGameController.cpp
src/client/systems/ClientGameController.hpp
src/client/systems/NetworkingClient.hpp
src/common/CMakeLists.txt
src/common/events/Event.hpp
src/common/events/EventController.cpp
src/common/events/PlayerCreatedEvent.hpp
src/common/objects/CircleGameObject.cpp
src/common/objects/CircleGameObject.hpp
src/common/objects/Group.cpp
src/common/objects/Group.hpp
src/common/objects/Mine.cpp
src/common/objects/Mine.hpp
src/common/systems/GameController.cpp
src/common/systems/GameController.hpp
src/common/systems/GameObjectController.cpp
src/common/systems/GameObjectController.hpp
src/common/systems/GameObjectStore.cpp
src/common/systems/GameObjectStore.hpp
src/common/systems/MineController.cpp
src/server/main.cpp
src/server/systems/NetworkingServer.cpp
src/server/systems/NetworkingServer.hpp
src/server/systems/ServerGameController.cpp
src/server/systems/ServerGameController.hpp
tests/client/systems/tests-ClientGameController.cpp
tests/server/systems/tests-ServerGameController.cpp

[0a2be30] Split game loop into preUpdate, update, postUpdate
[84a9c60] Create GameObjectController
- The GameObjectController is in charge of updating all game objects and
extracting/applying game state from/to them. It owns Player/Group/Mine
controllers.
- GameObjectController communicates with NetworkingServer/Client via
events.
[e85d352] Disable ClientGameController test
- ClientGameController needs a window to run and travis-ci's tests fail
because it can't open a window
- Add todos for issues
- Spawn mines
[3040f39] Minor cleanup

Game loop improvements

---

src/client/main.cpp
src/client/systems/ClientGameController.cpp
src/client/systems/ClientGameController.hpp
src/client/systems/NetworkingClient.cpp
src/client/systems/NetworkingClient.hpp
src/common/util/game_settings.hpp
src/server/systems/NetworkingServer.cpp
src/server/systems/NetworkingServer.hpp
tests/client/systems/tests-ClientGameController.cpp

Fixes #108 
[8fbd79a] Move game loop from main to ClientGameController
- main now just calls client_game_controller.start()
[201959d] Get player id from server during registration
- Now when the game loop starts will be guaranteed to have the player id
- We get the player id by continously sending tcp commands to the server
until we get a response. We need to do this because the server doesn't
immedietely have the player id when the client registers. The server
can't send the player id over the tcp socket once it's available because
it doesn't have a socket (the socket is only available when the client
sends a tcp request).

Connecting state

---

src/client/systems/ClientGameController.cpp
src/common/util/game_settings.hpp

Fixes  #102
I've disabled replay because it's resulting in a more jittery and undesirable experience. I can't tell if it's not implemented correctly or if it's just not what we want.

Fix interpolation replay bug and add flag to disable it

---

src/common/objects/CircleGameObject.hpp
src/common/objects/Mine.cpp
src/common/objects/Mine.hpp
src/common/rendering/RenderingDef.hpp
src/common/systems/GameController.cpp
src/common/systems/GameObjectController.cpp
src/common/systems/GameObjectController.hpp
src/common/systems/GameObjectStore.cpp
src/common/systems/GroupController.cpp
src/common/systems/GroupController.hpp
src/common/systems/MineController.cpp
src/common/systems/MineController.hpp
src/common/systems/ResourceController.cpp
src/common/systems/ResourceController.hpp
src/common/util/game_def.hpp
src/common/util/game_settings.hpp

*Group mines full capacity of mine.*
*Notice player's resource count rising on top right and how mine turns white when empty*
**Fixes**
Fixes #14 
**Commits**
[8c7b1de] Mining mechanism
- Mines now have a resource type and count. Their color is set according to their resource type and they will turn white when their count reaches 0. They start with a count of 4 for now.
- On collision, if the circles are a group and a mine, for each player in the group a single resource will be moved from the mine to the player.

Mining mechanism

---

src/client/rendering/AnimatedSprite.cpp
src/client/rendering/AnimatedSprite.hpp
src/client/rendering/AnimationController.cpp
src/client/rendering/RenderingController.cpp
src/common/objects/Group.cpp
src/common/objects/Mine.cpp
src/common/rendering/DirectionArrows.cpp
src/common/rendering/RenderingDef.hpp
src/common/util/game_settings.hpp
tests/client/rendering/tests-AnimatedSprite.cpp
tests/client/rendering/tests-AnimationController.cpp

Create constants for graphics.
*RenderingDef.hpp*
```cpp
// Group colors
const sf::Color DEFAULT_GROUP_COLOR(sf::Color::Transparent);
const sf::Color DEFAULT_GROUP_OUTLINE_COLOR(sf::Color::Black);
const sf::Color JOINABLE_COLOR(227, 102, 68);
const sf::Color UNGROUP_COLOR(sf::Color::Blue);
const sf::Color DIRECTION_ARROW_COLOR(63, 154, 233);
// Resource colors
const sf::Color DARKEST_COLOR(66, 118, 118);
const sf::Color DARK_COLOR(63, 157, 130);
const sf::Color LIGHT_COLOR(161, 205, 115);
const sf::Color LIGHTEST_COLOR(236, 219, 96);
// Mine colors
const sf::Color DEFAULT_MINE_COLOR(sf::Color::Red);
const sf::Color EMPTY_MINE_COLOR(155, 155, 155);
const std::array<sf::Color, RESOURCE_TYPE_COUNT> MINE_COLORS = {
RenderingDef::DARKEST_COLOR, RenderingDef::DARK_COLOR, …
```

Create constants for graphics

---

.travis.yml
CMakeLists.txt
README.md

Configure `CMakeLists.txt` to add the flags `-Wall -g -fsanitize=address -fno-omit-frame-pointer` in debug mode.
I tested the speeds of the release and debug builds and didn't notice a big difference:
```
cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
cmake --build build -- -j  128.69s user 9.32s system 202% cpu 1:08.16 total
cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
cmake --build build -- -j  130.05s user 7.21s system 257% cpu 53.341 totall
```
**Fixes**
Fixes  #78
**Commits**
[f3d4f8e] Cmake debug and release flags
[ade3b65] Travis compile debug build

Cmake debug and release flags

---

src/common/objects/CircleRigidBody.cpp
src/common/objects/CircleRigidBody.hpp
src/common/physics/PhysicsDef.hpp

Enforce max velocity to avoid teleportation situations such as a circle bouncing between two other circles and getting *really* fast *really* quickly.
This also helps avoid circles jumping over each other. Our collision system doesn't detect continuous collision.
**Fixes**
Fixes #99
**Commits**
[b37f397] Enforce max velocity
- Max velocity is proportional to player movement speed. Currnetly 4x
- Move physics constants to PhyscisDef.hpp
[7404e5f] Fix bug where target velocity is not updated when velocity is set

Enforce max velocity

---

src/client/rendering/DebugUIElement.cpp
src/client/rendering/RenderingController.cpp
src/client/rendering/RenderingController.hpp
src/client/rendering/ResourceUIElement.cpp
src/common/CMakeLists.txt
src/common/rendering/RenderingDef.hpp
src/common/rendering/RenderingUtil.cpp
src/common/rendering/RenderingUtil.hpp
src/common/systems/GameObjectController.cpp
src/common/systems/GameObjectController.hpp
src/common/systems/GroupController.cpp
src/common/systems/GroupController.hpp
src/common/util/game_settings.hpp

Display group players.
**Fixes**
Fixes #129
**Commits**
[ee62e17] Draw group player ids on each group
- Create a new function called drawUI for GameObjectControllers that
draws game object specfic UI on top of each game object. These are drawn
onto the winow rather than the buffer so that they are not scaled.
- Move some rendering constants to RenderingDef
- Create RenderUtil for rendering utility functions
[8709a2a] Minor fix

Display group players

---

resources/shaders/voronoi.frag
run.sh
src/client/rendering/RenderingController.cpp
src/client/rendering/RenderingController.hpp
src/client/systems/InputController.cpp
src/common/CMakeLists.txt
src/common/objects/CircleGameObject.cpp
src/common/objects/Group.cpp
src/common/objects/Group.hpp
src/common/objects/Mine.cpp
src/common/objects/Player.cpp
src/common/objects/Player.hpp
src/common/physics/VectorUtil.hpp
src/common/rendering/DirectionArrows.hpp
src/common/rendering/DirectionLines.cpp
src/common/rendering/DirectionLines.hpp
src/common/rendering/RenderingDef.hpp
src/common/rendering/RenderingUtil.cpp
src/common/rendering/RenderingUtil.hpp
src/common/systems/GameObjectController.hpp
src/common/systems/GroupController.cpp
src/common/systems/GroupController.hpp
src/common/systems/PlayerController.cpp
src/common/util/InputDef.cpp
src/common/util/InputDef.hpp
src/common/util/game_settings.hpp

Draws  lines around groups which point in members' directions and are colored in their intended resources.
If several players point in the same direction the line gets longer and shows in strips of color.
*Here you can see all five members of the group pointing in the same direction. Two of the players intend blue, one yellow, one orange and one red*
*An example with more members and directions*
!! Player desire is still WIP !!
**Fixes**
Fixes #138
**Commits**
[a22aa98 | b4d32c4] Set number of clients via command line parameter for run.sh
[9b3141b] Exit run.sh if build fails
[63a30e7] Draw direction lines
[6113738] Clean up direction line code
- Document
- Create a strippedLine utility function that creates the line
- Create constants for defining how the direction lines …

Group direction/intent lines

---

resources/shaders/voronoi_counts.frag
src/client/rendering/DrawableGroup.cpp
src/client/rendering/DrawableMine.cpp
src/client/rendering/DrawableMine.hpp
src/client/rendering/GameObjectRenderer.cpp
src/client/rendering/RenderingDef.hpp
src/common/objects/Mine.hpp
src/common/systems/MineController.cpp

Show mine resource count with voronoi_counts shader.
**Fixes**
Fixes #132 
**Commits**
[3f10515] Show mine resource count
- Mines now use the same shaders as groups to show how much resource
they contain
- Modify voronoi_counts shader to render transparent instead of white
for default cells
- Add outline to mine

Show mine resource count

---

src/client/main.cpp
src/client/rendering/RenderingDef.hpp
src/client/systems/ClientGameController.cpp
src/client/systems/ClientGameController.hpp
src/common/CMakeLists.txt
src/common/systems/GameController.cpp
src/common/systems/GameController.hpp
src/common/systems/GameObjectController.cpp
src/common/systems/GameObjectController.hpp
src/common/systems/GameObjectStore.cpp
src/common/systems/LevelController.cpp
src/common/systems/LevelController.hpp
src/common/systems/MineController.cpp
src/common/util/game_settings.hpp
src/server/CMakeLists.txt
src/server/main.cpp
src/server/systems/ServerGameController.cpp
src/server/systems/ServerGameController.hpp

Allows defining levels and loading them via command line arguments.
*e.g.*
```
./build/src/server/ug-server --level 1
```
Also adds a `--help` cli:
```
➜ ./build/src/client/ug-client -h
The client for Ungroup - a game about temporary allainces.
Usage:
Ungroup Client [OPTION...]
-h, --help           Displays options.
-x, --headless       Runs game without updating window.
-b, --bot            Runs game using a bot.
-a, --server-ip arg  The server's IP address in CIDR notation (ex.
127.0.0.1)
-s, --strategy arg   Runs game using specified strategy. Options are
Random, NearestGreedy.
```
```
➜ ./build/src/server/ug-server --help
The server for Ungroup - a game about temporary allainces.
Usage:
Ungroup Server [OPTION...]
-h, --help       Displays options.
-l, --level arg …
```

Level loading system

---

src/client/rendering/RenderingController.cpp
src/client/rendering/RenderingController.hpp
src/client/rendering/RenderingDef.hpp

*Connecting screen*
*Winner screen*
**FIxes**
Nothing

Connecting and winner screen visuals

---

src/common/util/game_settings.hpp
src/server/systems/NetworkingServer.cpp

* increase TCP timeout to 300 ms for more resiliency
* add support for operating with clients behind Symmetric NATs
** these NATs will rewrite the source port of UDP traffic from the
client which meant the server using the UDP port it gets from the client
via the intial registration over the TCP connection (registerClient),
wasn't working. The NAT would just drop the traffic since the
destination port didn't match the source port it had used for sending
out the client's nat_punch.
* set server UDP port to a fixed port: 4845. Simplifies firewall rule
configuration.
**Fixes**
Fixes #164

Improve server networking

---

src/client/CMakeLists.txt
src/common/metrics/TemporalMetric.cpp
src/common/metrics/TemporalMetric.hpp
tests/CMakeLists.txt
tests/common/metrics/tests-TemporalMetric.cpp

- Iterate over counts to accumulate instead of creating a flattened list
Client now runs at 30% cpu on my mac. Before it was 99%...
**Fixes**
Fixes #169

Imporve performance of TemporalMetric

---

resources/shaders/voronoi_counts.frag
src/client/rendering/DrawableGroup.cpp
src/client/rendering/RenderingDef.hpp

- Group now has a shadow instead of outline. The purpose of the shadow
is for the group to be visable even when it doesn't have any resources
- Group's joinable outline is now white and is slightly detached from
the group.

Remove group outline

---

resources/shaders/voronoi_counts.frag
src/client/rendering/DrawableMine.cpp
src/client/rendering/RenderingDef.hpp

- Voronoi count shader now tries to draw as many cells as possible for
each color fairly when there are more resources than MAX_CELL_COUNT. It
loops over the resource counts and adds one of each color as long as
there are any left.
- Remove mine border
**Fixes**
Fixes #159

Make voronoi count shader work with low cell count

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/client/CMakeLists.txt
src/client/rendering/AnimatedSprite.cpp
src/client/rendering/BaseUIElement.hpp
src/client/rendering/RenderingDef.hpp
src/client/systems/ClientGameController.cpp
src/client/systems/ClientGameController.hpp
src/client/systems/NetworkingClient.cpp
src/client/systems/NetworkingClient.hpp
src/common/CMakeLists.txt
src/server/CMakeLists.txt
src/server/systems/NetworkingServer.cpp
src/server/systems/NetworkingServer.hpp

- Link dependencies to client-lib and server-lib before, in turn, linking them to their executables
- See the path I took to discover this here: https://en.sfml-dev.org/forums/index.php?topic=27152.0
- Windows build having trouble with `uint` so I replaced them all with `uint32_t`
- Add cmake var `GUNGROUP_STATIC` to statically link sfml and gcc stuff
- Remove redundant `-std=c++11 ` from `CMAKE_CXX_FLAGS `
- Downgrade boost requirement to 1.55 because I couldn't find 1.65 on windows
- Handle `-pthreads` in a generic way with CMake's `find_package(Threads)`.
**Fixes**
Fixes #178

Update cmake to build on windows

---

.travis.yml
CMakeLists.txt
README.md
src/CMakeLists.txt

| Variable  | Meaning |
| ------------- | ------------- |
| UNGROUP_STATIC | Statically link SFML  |
| BUILD_TESTS  | Build tests  |
| ONLY_SERVER  | Only build server  |
| ONLY_CLIENT  | Only build client  |
**Fixes**
Fixes #195

Add cmake vars for building only client, server or tests
