SourenP/ungroup_game

src/client/main.cpp, src/common/Circle.hpp, src/common/util.hpp, src/server/GameController.cpp, src/server/NetworkingServer.cpp, src/server/NetworkingServer.hpp
I changed background color to Black. Third client was always white for
me so it wouldn't appear for me.
Fixed a use-after-free in clients list by removing the disconnected
client from the clients list.
Fixed compilation errors due to missing includes. Seems to only hapen in
Linux.
=> Bunch of bug fixes

src/client/NetworkingClient.cpp, src/client/NetworkingClient.hpp, src/common/ThreadSafeVector.hpp, src/common/game_state.cpp, src/common/game_state.hpp, src/server/NetworkingServer.cpp
This will allow us to easily add more data into the game state and while keeping the pack/unpack code up to date
=> GameState struct with packet unpacker/packer

src/.travis.yml
Trying to configure coverity scan to do continuous security analysis.
=> Add a travis CI config

src/.travis.yml
Add dependencies for building sfml. Specify language and compiler.
=> Fix travis config

.travis.yml, src/server/NetworkingServer.cpp, src/tests/integration/smoke_tests.js
500 milliseconds is a flaky value. Timeout should be 1 second
to void flip floppitiness.
=> Fix smoke test

src/client/Client.cpp, src/client/ClientGroup.cpp, src/client/ClientMine.cpp, src/common/Circle.cpp, src/common/CircleGameObject.cpp, src/common/CircleRigidBody.cpp, src/server/GameController.cpp, src/server/Group.cpp, src/server/LevelController.cpp, src/server/Mine.cpp, src/server/NetworkingServer.cpp, src/server/Player.cpp
two spaces after breaking param line
e.g.
```
void too_long(int a,
int b):
initThis() {
}
```
=> Fix function param style

src/client/systems/ClientGameController.cpp, src/common/CMakeLists.txt, src/common/objects/Group.cpp, src/common/objects/Group.hpp, src/common/systems/GameController.cpp, src/common/systems/GameController.hpp, src/common/systems/GameObjectStore.cpp, src/common/systems/GameObjectStore.hpp, src/common/systems/GroupController.cpp, src/common/systems/GroupController.hpp, src/common/util/game_settings.hpp, src/common/util/game_state.cpp, src/common/util/game_state.hpp, src/server/systems/NetworkingServer.cpp, src/server/systems/ServerGameController.cpp
- Rename LevelController to GameObjectStore
- Create GroupController
=> Game object controllers

src/client/systems/ClientGameController.cpp, src/common/CMakeLists.txt, src/common/events/EventController.cpp, src/common/events/EventController.hpp, src/common/factories/IdFactory.cpp, src/common/factories/IdFactory.hpp, src/common/objects/Mine.cpp, src/common/systems/GameController.cpp, src/common/systems/GameController.hpp, src/common/systems/GameObjectStore.cpp, src/common/systems/MineController.cpp, src/common/systems/MineController.hpp, src/common/systems/PlayerController.cpp, src/common/systems/PlayerController.hpp, tests/client/systems/tests-ClientGameController.cpp, tests/common/events/tests-EventController.cpp, tests/common/factories/tests-IdFactory.cpp, tests/common/objects/tests-CircleRigidBody.cpp, tests/server/systems/tests-ServerGameController.cpp, tests/tests-main.cpp
Since singleton instances were being shared between tests I wrote reset methods for the singleton classes and called them at test setup.
=> Create MineController, test setup/teardown and singleton reset methods

src/common/physics/CollisionUtil.cpp, tests/common/physics/tests-CollisionUtil.cpp
=> Fix collision position and corresponding tests

resources/shaders/voronoi.frag
=> Voronoi shader dynamic point count

.gitignore, src/common/CMakeLists.txt, src/common/rendering/DirectionArrows.hpp, src/common/systems/ResourceController.cpp, src/common/systems/ResourceController.hpp, src/common/util/game_settings.hpp, tests/CMakeLists.txt, tests/common/factories/tests-IdFactory.cpp, tests/common/systems/tests-ResourceController.cpp
*todo*
**Fixes**
Fixes  #38
**Commits**
[851f9e4] Create ResourceController
- Keeps track of resource counts for ids
[2454132] Minor fixes
=> Resource Mechanism

run.sh
The script builds the entire game, creates a server and two clients in a
tmux session. Very useful if you just want to get a game up without
juggling terminal windows.
=> Add a bash script to run a basic game locally

build.sh, run.sh
Adds a build script which supports both Ninja and CMake directly, then switches run.sh to use the new build script.
=> Update run script add build script

src/client/rendering/BackgroundController.cpp, src/client/rendering/BackgroundController.hpp, src/common/rendering/RenderingDef.hpp
Add support for background shader in `BackgroundController`.
**Fixes**
Nothing
**Commits**
[c3d0d41] Add support for background shader
=> Add support for background shader

src/client/main.cpp, src/client/systems/ClientGameController.cpp, src/client/systems/ClientGameController.hpp, src/client/systems/NetworkingClient.cpp, src/client/systems/NetworkingClient.hpp, src/common/util/game_def.hpp, src/common/util/game_settings.hpp, src/server/systems/NetworkingServer.cpp, src/server/systems/NetworkingServer.hpp
* Send regular no-op UDP packets for NAT traversal
* Add support for using dynamic client IP
* Add support for passing server IP from client cmd line
**Fixes**
Fixes #156, #155, #154
=> Fix internet networking

src/client/rendering/BackgroundController.cpp, src/client/rendering/BackgroundController.hpp, src/client/rendering/RenderingController.cpp, src/client/rendering/RenderingDef.hpp, src/common/util/game_settings.hpp
- Make game scale independent of window size
=> Fix game scale

src/client/rendering/DirectionArrows.cpp, src/client/rendering/DirectionArrows.hpp, src/client/rendering/DrawableGroup.cpp, src/client/rendering/DrawableGroup.hpp, src/client/rendering/RenderingDef.hpp, src/common/objects/Player.cpp, src/common/objects/Player.hpp
=> Sync player intent over network and set direction arrow to intent color

src/client/systems/InputController.cpp, src/client/systems/NetworkingClient.cpp, src/client/systems/NetworkingClient.hpp, src/common/systems/PlayerController.cpp, src/common/util/InputDef.cpp, src/common/util/InputDef.hpp
- Make toggle intent a reliable update
- Send unreliable input even if it hasn't changed 
**Fixes**
N/A
=> Continuously send unreliable updates

resources/configs/game_settings.json, src/client/rendering/RenderingDef.hpp, src/client/systems/ClientGameController.cpp, src/client/systems/ClientGameController.hpp, src/client/systems/NetworkingClient.cpp, src/client/systems/NetworkingClient.hpp, src/common/util/game_settings.cpp, src/common/util/game_settings.hpp
- Make replay code cleaner
- Add tick delta threshold for replay
- This can be set in `resources/configs/game_settings.json`
**Fixes**
Fixes #186
=> Clean up rewind and replay code

scripts/run_server.rb, src/client/main.cpp, src/client/systems/ClientGameController.cpp, src/client/systems/ClientGameController.hpp, src/client/systems/NetworkingClient.cpp, src/client/systems/NetworkingClient.hpp, src/server/main.cpp, src/server/rendering/TerminalRenderingController.cpp, src/server/rendering/TerminalRenderingController.hpp, src/server/systems/NetworkingServer.cpp, src/server/systems/NetworkingServer.hpp, src/server/systems/ServerGameController.cpp, src/server/systems/ServerGameController.hpp
*Add live tick to server UI*
*Add option to specify TCP port to listen on / connect to on server / client respectively*
*Show TCP port server is listening on in server UI*
*Add script to launch the server on an available TCP port, optionally opens firewall rules on Fedora*
=> various server improvements

src/client/main.cpp, src/client/systems/ClientGameController.cpp, src/client/systems/ClientGameController.hpp, src/common/bots/Bot.cpp, src/common/bots/Bot.hpp, src/common/systems/GameObjectController.cpp, src/common/systems/GameObjectController.hpp, src/common/systems/MineController.hpp, src/server/main.cpp, src/server/rendering/TerminalRenderingController.cpp, src/server/systems/ServerGameController.cpp, src/server/systems/ServerGameController.hpp
Move into ClientGameController and simplify how data is passed in by
just passing in GameObjectController. Means I don't have to update
function definitions every time I want to pass any data...
Also, I fixed the greedy bot to actually take into account the win
conditions, instead of dumbly trying to consume _all_ resources.
Description of changes
**Fixes**
Fixes #X
=> Refactor bot code

resources/shaders/voronoi_counts.frag, src/client/rendering/DirectionArrows.cpp, src/client/rendering/DrawableGroup.cpp, src/client/rendering/DrawableGroup.hpp, src/client/rendering/GameObjectRenderer.cpp, src/client/rendering/RenderingDef.hpp, src/common/systems/GroupController.cpp, src/common/systems/GroupController.hpp, src/common/systems/PlayerController.cpp, src/common/systems/PlayerController.hpp
_Group with three players_
**Fixes**
Fixes #208
=> Fade other players' directions in group

resources/configs/game_settings.json, resources/shaders/voronoi_counts.frag, src/client/rendering/DrawableGroup.cpp, src/client/rendering/DrawableMine.cpp, src/client/rendering/RenderingDef.hpp
=> Fix voronoi shader misalignment
